def display_menu():
    print("\n" + "=" * 60)
    print("               STUDENT TASK & STUDY PLANNER")
    print("              Plan. Track. Complete. Improve.")
    print("=" * 60)

    print("\n  TASK MANAGEMENT")
    print("  " + "-" * 58)
    print("  [1]  Add Task")
    print("  [2]  View Tasks")
    print("  [3]  Search Tasks")
    print("  [4]  Update Task")
    print("  [5]  Delete Task")
    print("  " + "-" * 58)

    print("\n  PROGRESS")
    print("  " + "-" * 58)
    print("  [6]  Mark Task Complete")
    print("  [7]  View Pending Tasks")
    print("  [8]  Filter Tasks")
    print("  " + "-" * 58)

    print("\n  DEADLINES")
    print("  " + "-" * 58)
    print("  [9]  View Overdue Tasks")
    print("  [10] View Upcoming Tasks")
    print("  " + "-" * 58)

    print("\n  INSIGHTS")
    print("  " + "-" * 58)
    print("  [11] Analytics")
    print("  [12] Productivity Report")
    print("  " + "-" * 58)

    print("\n  EXIT")
    print("  " + "-" * 58)
    print("  [13] Exit")
    print("  " + "-" * 58)
    print("\n" + "=" * 60)